# Generated by Django 5.0.6 on 2024-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_name', models.CharField(max_length=20, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cooking_steps', models.TextField(verbose_name='Шаги приготовления')),
                ('cooking_time', models.TimeField(verbose_name='Время приготовления')),
                ('image', models.ImageField(default=None, upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
                ('author', models.TextField(max_length=30, verbose_name='Автор')),
                ('date_of_addition', models.DateField(auto_now=True)),
                ('category', models.ManyToManyField(to='users.categoryrecept')),
            ],
        ),
    ]
