# Generated by Django 5.0.6 on 2024-06-08 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_recept_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Ингридиенты'),
            preserve_default=False,
        ),
    ]
