# Generated by Django 5.0.6 on 2024-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recept_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='image',
            field=models.ImageField(default=None, upload_to='recept foto/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
