# Generated by Django 5.0.6 on 2024-06-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_recept_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='image',
            field=models.ImageField(default=None, upload_to='foto/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
