# Generated by Django 5.0.6 on 2024-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_recept_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='recept_name',
            field=models.CharField(max_length=50, verbose_name='Название блюда'),
        ),
    ]
