# Generated by Django 5.0.6 on 2024-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_recept_recept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='cooking_time',
            field=models.CharField(max_length=5, verbose_name='Время приготовления'),
        ),
    ]
