# Generated by Django 5.0.6 on 2024-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_recept_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='cooking_time',
            field=models.CharField(max_length=10, verbose_name='Время приготовления'),
        ),
    ]
